name: Me
favicon: null
layout_spectrum: 0.86826
typography_spectrum: 0.39018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#394d54'
    - '#039bc6'
    - '#bfdbe0'
    - '#000000'
    - '#91aaaf'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
